version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "empops"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    volumes:
      - ./db:/var/lib/mysql
